name: Daily NSE Update

on:
  schedule:
    - cron: '30 2 * * *' # Runs daily at 08:00 AM IST (02:30 UTC)
  workflow_dispatch: # Allows manual run button

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create Service Account Key File
        run: echo '${{ secrets.GCP_SERVICE_ACCOUNT }}' > service_account.json

      - name: Run Fetch Script
        run: python update_stock_sheet.py
